name: spras
channels:
  - conda-forge
dependencies:
  - bioconda::snakemake-minimal=7.18.2
  - docker-py=5.0
  - networkx=2.8
  - pandas=1.4
  - pytest=7.1
  - python=3.8
  - pip=22.1
  - requests=2.28
  - spython=0.2
  # Only required for GraphSpace
  - commonmark=0.9
  - docutils=0.18
  - jinja2=3.1
  - mock=4.0
  - recommonmark=0.7
  - sphinx=5.0
  - pip:
     - graphspace_python==1.3.1
     - sphinx-rtd-theme==1.0.0
